require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FuerteApache' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'GoogleMaps'
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  target 'FuerteApacheTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'FuerteApache-tvOS' do
  # Pods for FuerteApache-tvOS

  target 'FuerteApache-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
